spring:
  output:
    ansi:
      enabled: always

  profiles:
    active: dev

  mvc:
    throw-exception-if-no-handler-found: true
    pathmatch:
      matching-strategy: ant_path_matcher
  web:
    resources:
      add-mappings: false

jwt:
  header: Authorization
  secret: eWFwcC1maXRmdHktc3ByaW5nLWJvb3QtYmFja2VuZC1zZWNyZXQteWFwcC1maXRmdHktc3ByaW5nLWJvb3QtYmFja2VuZC1zZWNyZXQK
  # expire : 365 * 24 * 60 * 60
  token-validity-in-seconds: 3153600

kakao:
  redirect_uri: http://52.79.144.104:8080/api/v1/auth/kakao/callback
  #  redirect_uri: http://localhost:8080/api/v1/auth/kakao/callback
  client_id: 31e815075078c89d7505decdeed8af98