
## 2. Production Env
server:
  port: 8080

spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${{ secrets.DATASOURCE_URL }}
    username: ${{ secrets.DATASOURCE_NAME }}
    password: ${{ secrets.DATASOURCE_PASSWORD }}
    driver-class-name: com.mysql.cj.jdbc.Driver
    sql-script-encoding: UTF-8


  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL8Dialect
    #    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    #    properties:
    #      hibernate:
    #        format_sql: true
    #        implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    #        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    #        hbm2ddl.auto: update
    #           use_sql_comments: true
    #           default_batch_fetch_: 100
    open-in-view: false
    show-sql: true

kakao:
  redirect_uri: http://52.79.144.104:8080/api/v1/auth/kakao/callback
