## 1. Development Env
server:
  port: 8080

#  spring.datasource.url=jdbc:h2:~/test;
#  spring.datasource.driverClassName=org.h2.Driver
#  spring.datasource.username=sa
#  spring.datasource.password=
#  spring.jpa.database-platform=org.hibernate.dialect.H2Dialect


spring:
  config:
    activate:
      on-profile: dev

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:~/test
    driver-class-name: org.h2.Driver
    username: test
    password: test
  #  datasource:
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  #    url: "jdbc:mysql://localhost/fitfty?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=UTC&tinyInt1isBit=false"
  #    username: root
  #    password: 1234
  #    hikari:
  #      auto-commit: false
  #      connection-test-query: SELECT 1
  #      minimum-idle: 10
  #      maximum-pool-size: 50
  #      transaction-isolation: TRANSACTION_READ_UNCOMMITTED

  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
    #    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    #    properties:
    #      hibernate:
    #        format_sql: true
    #        implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    #        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    #        hbm2ddl.auto: update
    #           use_sql_comments: true
    #           default_batch_fetch_: 100
    open-in-view: false
    show-sql: true


